default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: jing
  host: localhost


development:
  <<: *default
  database: sandwich_club_development

test:
  <<: *default
  database: sandwich_club_test
